CREATE TABLE USER_PROFILE(
	USER_NAME VARCHAR(10),
	FIRST_NAME VARCHAR(255),
	LAST_NAME VARCHAR(255),
	EMAIL VARCHAR(255)
);

CREATE TABLE USER_CREDENTIAL(
	USER_NAME VARCHAR(10),
	PASSWORD VARCHAR(10)
);